worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Кеш для отчётов
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=reports_cache:10m max_size=1g inactive=60m use_temp_path=off;

    server {
        listen 80;
        server_name localhost;

        location /reports/ {
            proxy_pass http://minio:9000/reports/;
            proxy_cache reports_cache;
            proxy_cache_key "$scheme$request_method$host$request_uri";
            proxy_cache_valid 200 302 60m;
            proxy_cache_valid 404 1m;
            add_header X-Cache-Status $upstream_cache_status;
            proxy_ignore_headers Cache-Control Expires;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Здоровье
        location /health {
            return 200 "OK\n";
            add_header Content-Type text/plain;
        }
    }
}